"""empty message

Revision ID: 179a6bd87bfa
Revises: dea66ee6e067
Create Date: 2020-04-04 15:13:20.412106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179a6bd87bfa'
down_revision = 'dea66ee6e067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
