"""empty message

Revision ID: 298fc643d194
Revises: 787a1e236519
Create Date: 2020-03-29 12:14:42.039611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298fc643d194'
down_revision = '787a1e236519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
