"""empty message

Revision ID: 2c072a3fb39f
Revises: e79c8d37fc21
Create Date: 2020-03-27 21:37:09.941757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c072a3fb39f'
down_revision = 'e79c8d37fc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.add_column('artist', sa.Column('website', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website')
    op.drop_column('artist', 'image_link')
    op.drop_column('artist', 'genres')
    op.drop_column('artist', 'facebook_link')
    # ### end Alembic commands ###
