"""empty message

Revision ID: 2d5935e41216
Revises: fbaec202953c
Create Date: 2020-03-28 16:45:23.789423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d5935e41216'
down_revision = 'fbaec202953c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'venue_id')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
