"""empty message

Revision ID: 5d7370363110
Revises: e8a3b9a17f86
Create Date: 2020-03-28 15:37:07.543663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7370363110'
down_revision = 'e8a3b9a17f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.String(length=120), nullable=True))
    op.add_column('show', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.add_column('show', sa.Column('venue_id', sa.String(length=120), nullable=True))
    op.drop_column('show', 'facebook_link')
    op.drop_column('show', 'city')
    op.drop_column('show', 'state')
    op.drop_column('show', 'genres')
    op.drop_column('show', 'phone')
    op.drop_column('show', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('show', 'venue_id')
    op.drop_column('show', 'start_time')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
