"""empty message

Revision ID: 787a1e236519
Revises: 946755bfdbb6
Create Date: 2020-03-29 12:07:02.279029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787a1e236519'
down_revision = '946755bfdbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_artist_id_fkey', 'show', type_='foreignkey')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('show_artist_id_fkey', 'show', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
