"""empty message

Revision ID: 8d7f71cd333a
Revises: f66d7bd86ea7
Create Date: 2020-03-27 09:19:44.176248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7f71cd333a'
down_revision = 'f66d7bd86ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'venue_id')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'seeking_description')
    # ### end Alembic commands ###
