"""empty message

Revision ID: 946755bfdbb6
Revises: c6350f5736f1
Create Date: 2020-03-29 11:01:57.836059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946755bfdbb6'
down_revision = 'c6350f5736f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
