"""empty message

Revision ID: c6350f5736f1
Revises: e8a3b9a17f86
Create Date: 2020-03-29 10:02:05.715375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6350f5736f1'
down_revision = 'e8a3b9a17f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.drop_column('show', 'genres')
    op.drop_column('show', 'city')
    op.drop_column('show', 'facebook_link')
    op.drop_column('show', 'state')
    op.drop_column('show', 'image_link')
    op.drop_column('show', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
