"""empty message

Revision ID: d070ac9c7801
Revises: fd99e25b2937
Create Date: 2020-03-29 12:25:43.091603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd070ac9c7801'
down_revision = 'fd99e25b2937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('show_venue_id_fkey', 'show', type_='foreignkey')
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('show_venue_id_fkey', 'show', 'venue2', ['venue_id'], ['id'])
    # ### end Alembic commands ###
