"""empty message

Revision ID: dea66ee6e067
Revises: 82f9cfc07a68
Create Date: 2020-04-04 14:55:31.720999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea66ee6e067'
down_revision = '82f9cfc07a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
