"""empty message

Revision ID: e79c8d37fc21
Revises: 8d7f71cd333a
Create Date: 2020-03-27 09:52:47.668532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79c8d37fc21'
down_revision = '8d7f71cd333a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('state', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'phone')
    op.drop_column('artist', 'city')
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###
