"""empty message

Revision ID: e8a3b9a17f86
Revises: e4585a84ad1f
Create Date: 2020-03-28 13:50:33.250215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a3b9a17f86'
down_revision = 'e4585a84ad1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('venue', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'id')
    # ### end Alembic commands ###
