"""empty message

Revision ID: fbaec202953c
Revises: 5d7370363110
Create Date: 2020-03-28 16:42:16.578421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaec202953c'
down_revision = '5d7370363110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'artist_id')
    op.drop_column('show', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('venue_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('artist_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
